import React, { useEffect, useRef, useState } from 'react';
import MonacoEditor, { Monaco } from '@monaco-editor/react';
import * as Y from 'yjs';
import { Socket } from 'socket.io-client';

interface RemoteUser {
  socketId: string;
  id: number;
  username: string;
  color: string;
  position?: { lineNumber: number; column: number };
  selection?: {
    startLineNumber: number;
    startColumn: number;
    endLineNumber: number;
    endColumn: number;
  };
}

interface EditorProps {
  socket: Socket;
  roomId: string;
  userId: number;
  username: string;
  language: string;
  onCodeChange?: (code: string) => void;
  yDoc: Y.Doc;
}

export const Editor: React.FC<EditorProps> = ({
  socket,
  roomId,
  userId,
  username,
  language,
  onCodeChange,
  yDoc
}) => {
  const [editorInstance, setEditorInstance] = useState<any>(null);
  const [monacoInstance, setMonacoInstance] = useState<Monaco | null>(null);
  const [remoteUsers, setRemoteUsers] = useState<Map<string, RemoteUser>>(new Map());
  
  const yText = yDoc.getText('codetext');
  const isApplyingRemoteChange = useRef(false);
  const decorationIdsRef = useRef<string[]>([]);

  // 1. Join Room and handle Yjs document sync
  useEffect(() => {
    // Listen to initial document sync from server
    const handleDocSync = (update: ArrayBuffer) => {
      isApplyingRemoteChange.current = true;
      Y.applyUpdate(yDoc, new Uint8Array(update));
      isApplyingRemoteChange.current = false;
      
      if (editorInstance) {
        editorInstance.setValue(yText.toString());
      }
      if (onCodeChange) {
        onCodeChange(yText.toString());
      }
    };

    // Listen to incremental updates from other clients
    const handleDocUpdate = (update: ArrayBuffer) => {
      isApplyingRemoteChange.current = true;
      Y.applyUpdate(yDoc, new Uint8Array(update));
      isApplyingRemoteChange.current = false;
    };

    socket.on('doc-sync', handleDocSync);
    socket.on('doc-update', handleDocUpdate);

    // Bind local Yjs update events to socket emissions
    const handleLocalYjsUpdate = (update: Uint8Array, origin: any) => {
      if (origin === 'monaco') {
        socket.emit('doc-update', update);
      }
      if (onCodeChange) {
        onCodeChange(yText.toString());
      }
    };
    yDoc.on('update', handleLocalYjsUpdate);

    return () => {
      socket.off('doc-sync', handleDocSync);
      socket.off('doc-update', handleDocUpdate);
      yDoc.off('update', handleLocalYjsUpdate);
    };
  }, [socket, yDoc, editorInstance, yText, onCodeChange]);

  // 2. Yjs observer for updating Monaco Editor content
  useEffect(() => {
    if (!editorInstance) return;

    const yTextObserver = (event: any) => {
      // Ignore updates that were generated by this Monaco editor
      if (event.transaction.origin === 'monaco') return;

      isApplyingRemoteChange.current = true;
      const model = editorInstance.getModel();
      if (model) {
        const edits: any[] = [];
        let offset = 0;

        for (const op of event.delta) {
          if (op.retain) {
            offset += op.retain;
          } else if (op.insert !== undefined) {
            const pos = model.getPositionAt(offset);
            edits.push({
              range: new monacoInstance!.Range(pos.lineNumber, pos.column, pos.lineNumber, pos.column),
              text: op.insert as string,
              forceMoveMarkers: true,
            });
          } else if (op.delete !== undefined) {
            const startPos = model.getPositionAt(offset);
            const endPos = model.getPositionAt(offset + op.delete);
            edits.push({
              range: new monacoInstance!.Range(startPos.lineNumber, startPos.column, endPos.lineNumber, endPos.column),
              text: '',
              forceMoveMarkers: false,
            });
            offset += op.delete;
          }
        }

        if (edits.length > 0) {
          editorInstance.executeEdits('yjs', edits);
        }
      }
      isApplyingRemoteChange.current = false;
    };

    yText.observe(yTextObserver);
    return () => {
      yText.unobserve(yTextObserver);
    };
  }, [editorInstance, monacoInstance, yText]);

  // 3. User cursor / selections sync
  useEffect(() => {
    // Update users list
    socket.on('users-update', (users: RemoteUser[]) => {
      const updatedMap = new Map<string, RemoteUser>();
      users.forEach((u) => {
        if (u.socketId !== socket.id) {
          updatedMap.set(u.socketId, u);
          injectCursorStyles(u);
        }
      });
      setRemoteUsers(updatedMap);
    });

    // Handle single cursor update
    socket.on('cursor-update', (data: RemoteUser) => {
      if (data.socketId === socket.id) return;
      
      setRemoteUsers((prev) => {
        const next = new Map(prev);
        next.set(data.socketId, data);
        return next;
      });
      injectCursorStyles(data);
    });

    // Remove user cursor on exit
    socket.on('user-left', (socketId: string) => {
      setRemoteUsers((prev) => {
        const next = new Map(prev);
        next.delete(socketId);
        return next;
      });
      const styleEl = document.getElementById(`cursor-styles-${socketId}`);
      if (styleEl) styleEl.remove();
    });

    return () => {
      socket.off('users-update');
      socket.off('cursor-update');
      socket.off('user-left');
    };
  }, [socket]);

  // Inject dynamic CSS style blocks for user-specific cursor colors
  const injectCursorStyles = (user: RemoteUser) => {
    const styleId = `cursor-styles-${user.socketId}`;
    let styleEl = document.getElementById(styleId);
    if (!styleEl) {
      styleEl = document.createElement('style');
      styleEl.id = styleId;
      document.head.appendChild(styleEl);
    }
    
    // Create cursor visual class, cursor label hover pseudo-element, and highlights.
    styleEl.innerHTML = `
      .cursor-${user.socketId} {
        border-left: 2px solid ${user.color};
      }
      .cursor-${user.socketId}::after {
        content: "${user.username}";
        position: absolute;
        top: -18px;
        left: 0;
        background-color: ${user.color};
        color: white;
        font-size: 10px;
        font-family: 'Outfit', sans-serif;
        font-weight: 500;
        padding: 1px 5px;
        border-radius: 3px;
        white-space: nowrap;
        opacity: 0;
        pointer-events: none;
        transition: opacity 0.2s ease-in-out;
        z-index: 100;
      }
      .cursor-${user.socketId}:hover::after {
        opacity: 1;
      }
      .selection-${user.socketId} {
        background-color: ${user.color}33; /* 20% opacity */
      }
    `;
  };

  // 4. Update Monaco Editor decorations for remote cursors/selections
  useEffect(() => {
    if (!editorInstance || !monacoInstance) return;

    const newDecorations: any[] = [];

    remoteUsers.forEach((user) => {
      // Draw Remote Cursor
      if (user.position) {
        newDecorations.push({
          range: new monacoInstance.Range(
            user.position.lineNumber,
            user.position.column,
            user.position.lineNumber,
            user.position.column
          ),
          options: {
            className: `remote-cursor cursor-${user.socketId}`,
            hoverMessage: { value: `**User:** ${user.username}` },
          },
        });
      }

      // Draw Remote Selection Highlights
      if (user.selection && (
        user.selection.startLineNumber !== user.selection.endLineNumber ||
        user.selection.startColumn !== user.selection.endColumn
      )) {
        newDecorations.push({
          range: new monacoInstance.Range(
            user.selection.startLineNumber,
            user.selection.startColumn,
            user.selection.endLineNumber,
            user.selection.endColumn
          ),
          options: {
            className: `remote-selection selection-${user.socketId}`,
          },
        });
      }
    });

    // Update decorations on Monaco
    decorationIdsRef.current = editorInstance.deltaDecorations(
      decorationIdsRef.current,
      newDecorations
    );
  }, [remoteUsers, editorInstance, monacoInstance]);

  const handleEditorDidMount = (editor: any, monaco: Monaco) => {
    setEditorInstance(editor);
    setMonacoInstance(monaco);

    // Set initial text value
    editor.setValue(yText.toString());

    // Listen to local typing modifications
    editor.onDidChangeModelContent((event: any) => {
      if (isApplyingRemoteChange.current) return;

      yDoc.transact(() => {
        for (const change of event.changes) {
          if (change.rangeLength > 0) {
            yText.delete(change.rangeOffset, change.rangeLength);
          }
          if (change.text.length > 0) {
            yText.insert(change.rangeOffset, change.text);
          }
        }
      }, 'monaco');
    });

    // Listen to local cursor / selection adjustments
    editor.onDidChangeCursorSelection((event: any) => {
      const position = editor.getPosition();
      const selection = editor.getSelection();

      socket.emit('cursor-move', {
        position,
        selection,
      });
    });
  };

  return (
    <div className="w-full h-full border border-dark-800 rounded-lg overflow-hidden shadow-2xl">
      <MonacoEditor
        height="100%"
        language={language}
        theme="vs-dark"
        onMount={handleEditorDidMount}
        options={{
          fontSize: 14,
          fontFamily: "'Fira Code', 'JetBrains Mono', monospace",
          minimap: { enabled: true },
          automaticLayout: true,
          padding: { top: 12, bottom: 12 },
          cursorBlinking: "smooth",
          cursorSmoothCaretAnimation: "on",
          smoothScrolling: true,
          scrollbar: {
            vertical: 'visible',
            horizontal: 'visible',
            verticalScrollbarSize: 8,
            horizontalScrollbarSize: 8
          }
        }}
      />
    </div>
  );
};
